### ISSUE TITLE
Features and AU labels not match

### ISSUE THREAD

**Issue by yufu** [haixpham/end2end_AU_speech#1]
Hi haixpham,
I have some trouble when reproduce your code.
I found my features length are always not equal to the AU labels when using RAVDESS dataset .
if it is right ?
Waiting for your reply, thanks a lot .

**Comment by haixpham** [comment]
Hi zuglerfu,
No, there are not that many mismatched input-label sequences. The reason is simply because the tracker may miss one or two frames of the video when the actor turns their face away from camera. You can run create_spectrogram_CTF.py to see the text message, there are a couple of dozens of those mismatched sequences at most.
